name: 'Webhook Reporter'
description: 'Sends coverage and failure reports to various providers like Discord.'
author: Mohamed Jama
inputs:
  coverage_file:
    description: 'Path to the coverage file'
    required: true
  provider:
    description: 'The provider to send the report to (e.g., discord, slack)'
    required: true
  webhook_url:
    description: 'The webhook URL for the provider'
    required: true
  test_results:
    description: "test results file"
    required: false
  coverage_threshold:
    description: "Percent threshold that we want coverage to be above."
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.coverage_file }}
    - ${{ inputs.provider }}
    - ${{ inputs.test_results }}
    - ${{ inputs.webhook_url }}
    - ${{ inputs.coverage_threshold }}